#+TITLE: DSA notes
#+STARTUP: overview

* Searching
** Binary Search
*** Time Complexity: $$\frac{N}{2^k} \to Olog(N)$$
*** Algorithm
- find middle element
- if (target == mid) return it
- if (target > mid) search the right half
  - else search the left half
- repeat until target == mid
*** Tricks
- in *digit* arrays after the searching loop finishes:
  - the *start* will be the (*ceil*) of the target.
  - the *end* will be the (*floor*) of the target.
- *first* occurance of target will always be the *left* side (end = mid - 1).
- *last* occuracne will be in the *right* side (start = mid + 1),
* Sorting
** In-place
*** Selection Sort

- Time complexity: O(n^2)
- Space complexity: O(1) (in-place)

  - الـselection sort بيختار عنصر ويفترض انه اصغر/اكبر عنصر في الـarray
  - بيقارنه مع باقي العناصر اللي بعده.
  - لو في عنصر اصغر/اكبر منه *بيبدل* معاه.

*** Bubble Sort

- Time complexity: O(n^2)
- Space complexity: O(1) (in-place)

  - الـbubble sort بيقارن كل عناصر الـarray ما عدا اخر رقم (n - 1 >).

  - لو الرقم اللي علي الشمال (i) اكبر من الرقم اللي علي اليمين (i + 1) هنبدلهم مع بعض, لاننا دائما في الترتيب التصاعدي بنزق الارقام الكبيرة علي اليمين.

  - بعد ما المقارنة تخلص, هنلاقي اكبر عنصر في الـarray بقا اخر عنصر في مكانه الطبيعي.

  - بس كدا احنا رتبنا رقم واحد بس, فا هنكرر المقارنة دي n - 1 مرة, وهنلاقي كل العناصر اترتبت.

*** InsertionSort

- Time Complexity: O(n^2)
- Space Complexity: O(1) (in-place)

  - الـinserstion sort بيقسم الـarray لجزء مرتب وجزء غير مرتب.
    - هنعتبر ان الجزء المرتب هو اول عنصر arr0
    - هنعمل loop من 1 الي n - 1, يعني بنـloop علي الجزء الغير مرتب فقط.
    - هنخزن العنصر الحالي في الجزء الغير مرتب في متغير tmp
    - هنقارنه بكل اللي قبله, (وكل اللي قبله ده اللي هو الجزء المرتب)
    - العناصر الاكبر هيتعملها shift لليمين, العنصر الاصغر هيفضل زي ما هو.
    - لحد ما الـj هتكون واقفة عند العنصر اللي قبل اللي احنا هنبدله مع الـtmp

#+begin_src java
static void inserstionSort(int[] arr) {
    for (int i = 1; i < arr.length; i++) {
        int tmp = arr[i]; // current element in the unsorted side;
        int j = i - 1; // last element in the sorted side

        // compare the tmp with all elements in the sorted side
        while (j >= 0 && arr[j] > tmp) {
            arr[j + 1] = arr[j]; // shift to right
            j--;
        }

        // stops at last sorted index - 1
        arr[j + 1] = tmp;
    }
}
#+end_src

*** CyclicSort

- Time Complexity:
  - n iterations + n swaps = O(n + n) => O(n)

- الـCyclic sort هي طريقة سريعة للـsort, بس بتشتغل فقط طول ما الارقام في الـrange من 1:n, يعني لازم يكون الـindex بتاع كل عنصر هو قيمته - 1.

- لكن لو في مسافات زي كدا =[10, 20, 30, 40, 50]= او =[1, 3, 4, 5]= مش هيشتغل كويس, لان حساب الـ =correctIdx= هيطلع غلط.

- فكرته بسيطة جدا, اننا نحط كل عنصر عند الـindex اللي بيساوي قيمته - 1.

- هنقارن كل عنصر بالعنصر اللي عند =index = value - 1=, ولو مش بيساوا بعض, هنبدلهم

- بس الفكرة هنا, ان الرقم اللي بدلنا معاه, مش شرط يكون ده فعلا مكانه, فا لازم نعيد نفس العملية تاني, لحد ما الرقمين اللي بيتبدلوا مع بعض يكون هما الاتنين اترتبوا مش واحد بس منهم.

- *اهم حاجة* ان الـpattern ده لازم يجي في ذهننا اول ما نسمع كلمة *range 1:n*

#+begin_src java
static void sort(int[] arr, boolean hasZero) {
    int i = 0;

    while (i < arr.length) {
        int correctIdx = hasZero ? arr[i] : arr[i] - 1;

        if (arr[i] != arr[correctIdx]) {
            int tmp = arr[i];
            arr[i] = arr[correctIdx];
            arr[correctIdx] = tmp;
        } else
            i++;
    }
}
#+end_src

* Array Rotation
*** 189. Rotate Array - https://leetcode.com/problems/rotate-array/

- Idea
  - Reverse whole array      -> [ *7, 6, 5, 4, 3, 2, 1* ]
  - Reverse first *k* numbers  -> [ *5, 6, 7*, 4, 3, 2, 1 ]
  - Reverse last *n-k* numbers -> [ 5, 6, 7, *1, 2, 3, 4* ]
  - =k = k % nums.length= is the most important statement in the entire code because if *k* > nums.length, the =reverse()= function will go out of bound, the modulo will reduce the *k* so not to exceed the nums.length
  - but if *k* < nums.length it will work fine without this statement.

#+begin_src java :dir /tmp :tangle ./solutions/array/medium/rotate_array_189/Solution.java
/*
  Given an integer array nums, rotate the array to the right by k steps, where k is non-negative.

Example 1:

Input: nums = [1,2,3,4,5,6,7], k = 3
Output: [5,6,7,1,2,3,4]
Explanation:
rotate 1 steps to the right: [7,1,2,3,4,5,6]
rotate 2 steps to the right: [6,7,1,2,3,4,5]
rotate 3 steps to the right: [5,6,7,1,2,3,4]
*/
import java.util.Arrays;

class Solution {
    public static void main(String args[]) {
        int[] arr = {1, 2, 3, 4, 5, 6, 7};
        rotate(arr, 3);
        System.out.println(Arrays.toString(arr));
    }

    static void rotate(int[] nums, int k) {
        k = k % nums.length;
        reverse(nums, 0, nums.length - 1);
        reverse(nums, 0, k - 1);
        reverse(nums, k, nums.length - 1);
    }

    static void reverse(int[] nums, int s, int e) {
        while (s < e) {
            int tmp = nums[s];
            nums[s] = nums[e];
            nums[e] = tmp;
            s++;
            e--;
        }
    }
}
#+end_src

#+RESULTS:
: [5, 6, 7, 1, 2, 3, 4]

------

- Simpler solution but with O(n) memory.

  - الفكرة كلها في الـ *modulo*, الـshift هو عبارة عن i + k ببساطة جدا, ولكن المشكلة اننا عاوزين لما الـ i + k يعدي الـarr يعمل flip.
  - الـmodulo بيساعدنا نحجم الـ i + k ونخليها تعمل flip.

#+begin_src java :dir /tmp
class  Solution {
    public static void main(String[] args) {
        int[] arr = {1, 2, 3, 4, 5, 6, 7};
        rotate(arr, 3);
        System.out.println(Arrays.toString(arr));
    }

    static void rotate(int[] nums, int k) {
        int[] res = new int[nums.length];

        for (int i = 0; i < nums.length; i++) {
            res[(i + k) % nums.length] = nums[i];
        }

        for (int i = 0; i < nums.length; i++) {
            nums[i] = res[i];
        }

    }
}
#+end_src

#+RESULTS:
: [5, 6, 7, 1, 2, 3, 4]
- Rotation count in any sorted array is *pivot + 1*.
* Math tricks & formulas
- Combination formula for pairs: =count * (count - 1) / 2=
